sudo: false
language: java

jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

# Overrides travis 'install' step.
# This installs dependencies using default profile.
install:
  - java -version
  - mvn --version
  - mvn --batch-mode clean compile

# overrides travis 'script' step
script:
  - mvn --batch-mode clean package

after_success:
  # using environment variable $repo_token set in travis web site
  - mvn clean test cobertura:cobertura coveralls:report -DrepoToken=$repo_token
  
notifications:
  email:
    on_success: never
    on_failure: always